Station monitoring + refacto + user register fix
vecolo-project/API pull request #7
Opened 2021-05-20 17:42 UTC by Nouuu

2021-05-21 18:22 UTC, SwannHERRERA requested changes
il faudrait rename la branch le nom est pas adapater a ce qu'elle fait + faute dans feature

2021-05-21 18:22 UTC, SwannHERRERA commented on src/api/middlewares/attachStation.ts
> +    const stationEntity: Station = await stationService.findOne(req.token.id);
le type c'est Station | null

2021-05-21 18:22 UTC, SwannHERRERA commented on src/api/services/StationService.ts
> +  generateToken(stationRecord: Station): string {
peut être faire 
```ts
  generateToken({ id }: Station): string {
    jwt.sign({ id }, config.jwtSecret);
  }
```

2021-05-21 18:22 UTC, SwannHERRERA commented on src/api/routes/stationMonitoring.ts
> +        StationMonitoring.create({
Cette fonction est longue et compliqué, elle fait beaucoup de chose qui ne sont pas de sa responsabilité. Je te propose de crée une méthode dans le service

2021-05-21 18:22 UTC, SwannHERRERA commented on package.json
> +    "build:prod": "cross-env NODE_ENV=production tsc -p .",
ça sert a rien de mettre l'environnement tsc transpile juste le typescript en javascript dans le dossier dist et il y a pas de transpilation conditionnel

2021-05-22 08:09 UTC, Huriumari approved these changes

2021-05-22 08:22 UTC, merged